#!/bin/bash

function resolve_host() {
    local targetdomain=$1
    local resolver=$2

    if [ -n $resolver ]; then
        dig +short $targetdomain | tail -n 1
    else
        dig +short $targetdomain @$resolver | tail -n 1
    fi
}

# Follows url ($1) redirects and returns the "effective url", the resulting URL
# after following all redirects.
function get_effective_url() {
    curl \
        -I \
        -s \
        -o /dev/null \
        -L \
        -w '%{url_effective}' \
        $1
}

# Takes seconds and outputs it as ms with a single decimal place
function s_to_ms() {
    echo "$(echo "scale=1;${1}*1000/1" | bc)ms"
}
